const fs=require('fs');
const path=require('path');
const INCIDENT='NEPAL-2026-08-26-FLOOD';
const DIR='data/source-snapshots';
function decode(s){return String(s||'').replace(/<script[\s\S]*?<\/script>/gi,' ').replace(/<style[\s\S]*?<\/style>/gi,' ').replace(/<[^>]*>/g,' ').replace(/&nbsp;/g,' ').replace(/&amp;/g,'&').replace(/&quot;/g,'"').replace(/&#039;|&#39;/g,"'").replace(/&#(\d+);/g,(_,n)=>String.fromCodePoint(Number(n))).replace(/\s+/g,' ').trim()}
function files(prefix){let a=[];try{a=fs.readdirSync(DIR).filter(x=>new RegExp(`^${prefix}-page-\\d+\\.html$`).test(x)).sort()}catch{};if(!a.length&&fs.existsSync(path.join(DIR,`${prefix}.html`)))a=[`${prefix}.html`];return a}
function field(text,label,nextLabels){const stop=nextLabels.map(x=>x.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')).join('|');const re=new RegExp(`${label}\\s*[:-]\\s*(.*?)(?=(?:${stop})\\s*[:-]|$)`,'i');const m=text.match(re);return m?m[1].trim():''}
function digits(s){const map={'०':'0','१':'1','२':'2','३':'3','४':'4','५':'5','६':'6','७':'7','८':'8','९':'9'};return String(s||'').replace(/[०-९]/g,d=>map[d])}
function parse(prefix,kind,hrefPrefix,status){const out=[];for(const file of files(prefix)){const html=fs.readFileSync(path.join(DIR,file),'utf8');const blocks=html.split(/<tr[^>]*>/i).slice(1);for(const block of blocks){const idm=block.match(new RegExp(`href=["'][^"']*${hrefPrefix}/?(\\d+)[^"']*["']`,'i'));if(!idm)continue;const source_record_id=idm[1];const text=decode(block);const labels=['नाम','उमेर','अन्दाजी उमेर','लिङ्ग','हराएको ठाउँ','हराएको मिति/समय','भेटिएको ठाउँ','भेटिएको मिति/समय','हाल शव राखेको स्थान','सम्भावित स्थान','प्रदेश','जिल्ला'];const name=field(text,'नाम',labels.filter(x=>x!=='नाम'))|| (kind==='body'?'Unidentified person':'Unknown name');const ageRaw=field(text,'उमेर',labels.filter(x=>x!=='उमेर'));const estRaw=field(text,'अन्दाजी उमेर',labels.filter(x=>x!=='अन्दाजी उमेर'));const sex=field(text,'लिङ्ग',labels.filter(x=>x!=='लिङ्ग'));const missingPlace=field(text,'हराएको ठाउँ',labels.filter(x=>x!=='हराएको ठाउँ'));const foundPlace=field(text,'भेटिएको ठाउँ',labels.filter(x=>x!=='भेटिएको ठाउँ'));const possible=field(text,'सम्भावित स्थान',labels.filter(x=>x!=='सम्भावित स्थान'));const foundDate=field(text,'भेटिएको मिति/समय',labels.filter(x=>x!=='भेटिएको मिति/समय'));const lostDate=field(text,'हराएको मिति/समय',labels.filter(x=>x!=='हराएको मिति/समय'));const storage=field(text,'हाल शव राखेको स्थान',labels.filter(x=>x!=='हाल शव राखेको स्थान'));const age=Number((digits(ageRaw).match(/\d+/)||[])[0])||null;const estimated_age=Number((digits(estRaw).match(/\d+/)||[])[0])||null;const location=missingPlace||foundPlace||possible||'';out.push({id:`${prefix}-${source_record_id}`,incident_id:INCIDENT,source:prefix==='POLICE_MISSING'?'NEPAL_POLICE_MISSING':prefix==='POLICE_FOUND'?'NEPAL_POLICE_FOUND':'NEPAL_POLICE_DISASTER_BODY',source_record_id,name,age,estimated_age,sex,status,location,found:foundPlace,detail:[lostDate&&`missing ${lostDate}`,foundDate&&`found ${foundDate}`,storage&&`held ${storage}`].filter(Boolean).join(' · '),source_url:`https://udb.nepalpolice.gov.np${hrefPrefix}/${source_record_id}`,raw_text:text});}}
return out}
const missing=parse('POLICE_MISSING','person','/missing','MISSING');
const found=parse('POLICE_FOUND','person','/found','LOCATED');
const bodies=parse('POLICE_DISASTER_BODIES','body','/dead-bodies','UNIDENTIFIED_BODY');
const generated_at=new Date().toISOString();
fs.writeFileSync('data/police-missing-latest.json',JSON.stringify({incident_id:INCIDENT,generated_at,records:missing},null,2)+'\n');
fs.writeFileSync('data/police-found-latest.json',JSON.stringify({incident_id:INCIDENT,generated_at,records:found},null,2)+'\n');
fs.writeFileSync('data/police-bodies-latest.json',JSON.stringify({incident_id:INCIDENT,generated_at,records:bodies},null,2)+'\n');
console.log(JSON.stringify({missing:missing.length,found:found.length,bodies:bodies.length},null,2));
