const fs=require('fs');
const path=require('path');
const INCIDENT='NEPAL-2026-08-26-FLOOD';
const DIR='data/source-snapshots';
function decode(s){return String(s||'').replace(/<script[\s\S]*?<\/script>/gi,' ').replace(/<style[\s\S]*?<\/style>/gi,' ').replace(/<[^>]*>/g,' ').replace(/&nbsp;/g,' ').replace(/&amp;/g,'&').replace(/&quot;/g,'"').replace(/&#039;|&#39;/g,"'").replace(/&#(\d+);/g,(_,n)=>String.fromCodePoint(Number(n))).replace(/\s+/g,' ').trim()}
function files(prefix){let a=[];try{a=fs.readdirSync(DIR).filter(x=>new RegExp(`^${prefix}-page-\\d+\\.html$`).test(x)).sort()}catch{};if(!a.length&&fs.existsSync(path.join(DIR,`${prefix}.html`)))a=[`${prefix}.html`];return a}
function prior(file){try{return JSON.parse(fs.readFileSync(file,'utf8')).records||[]}catch{return[]}}
function field(text,label,nextLabels){const stop=nextLabels.map(x=>x.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')).join('|');const re=new RegExp(`${label}\\s*[:-]\\s*(.*?)(?=(?:${stop})\\s*[:-]|$)`,'i');const m=text.match(re);return m?m[1].trim():''}
function digits(s){const map={'०':'0','१':'1','२':'2','३':'3','४':'4','५':'5','६':'6','७':'7','८':'8','९':'9'};return String(s||'').replace(/[०-९]/g,d=>map[d])}
function parse(prefix,kind,hrefPrefix,status){const sourceFiles=files(prefix),out=[];for(const file of sourceFiles){const html=fs.readFileSync(path.join(DIR,file),'utf8');const blocks=html.split(/<tr[^>]*>/i).slice(1);for(const block of blocks){const idm=block.match(new RegExp(`href=["'][^"']*${hrefPrefix}/?(\\d+)[^"']*["']`,'i'));if(!idm)continue;const source_record_id=idm[1],text=decode(block);const labels=['नाम','उमेर','अन्दाजी उमेर','लिङ्ग','हराएको ठाउँ','हराएको मिति/समय','भेटिएको ठाउँ','भेटिएको मिति/समय','हाल शव राखेको स्थान','सम्भावित स्थान','प्रदेश','जिल्ला'];const name=field(text,'नाम',labels.filter(x=>x!=='नाम'))||(kind==='body'?'Unidentified person':'Unknown name');const ageRaw=field(text,'उमेर',labels.filter(x=>x!=='उमेर')),estRaw=field(text,'अन्दाजी उमेर',labels.filter(x=>x!=='अन्दाजी उमेर'));const sex=field(text,'लिङ्ग',labels.filter(x=>x!=='लिङ्ग'));const missingPlace=field(text,'हराएको ठाउँ',labels.filter(x=>x!=='हराएको ठाउँ')),foundPlace=field(text,'भेटिएको ठाउँ',labels.filter(x=>x!=='भेटिएको ठाउँ')),possible=field(text,'सम्भावित स्थान',labels.filter(x=>x!=='सम्भावित स्थान'));const foundDate=field(text,'भेटिएको मिति/समय',labels.filter(x=>x!=='भेटिएको मिति/समय')),lostDate=field(text,'हराएको मिति/समय',labels.filter(x=>x!=='हराएको मिति/समय')),storage=field(text,'हाल शव राखेको स्थान',labels.filter(x=>x!=='हाल शव राखेको स्थान'));const age=Number((digits(ageRaw).match(/\d+/)||[])[0])||null,estimated_age=Number((digits(estRaw).match(/\d+/)||[])[0])||null;out.push({id:`${prefix}-${source_record_id}`,incident_id:INCIDENT,source:prefix==='POLICE_MISSING'?'NEPAL_POLICE_MISSING':prefix==='POLICE_FOUND'?'NEPAL_POLICE_FOUND':'NEPAL_POLICE_DISASTER_BODY',source_record_id,name,age,estimated_age,sex,status,location:missingPlace||foundPlace||possible||'',found:foundPlace,detail:[lostDate&&`missing ${lostDate}`,foundDate&&`found ${foundDate}`,storage&&`held ${storage}`].filter(Boolean).join(' · '),source_url:`https://udb.nepalpolice.gov.np${hrefPrefix}/${source_record_id}`,raw_text:text});}}
return {records:out,sourceFiles};}
function preserveIfUnavailable(parsed,file){const old=prior(file);if(parsed.sourceFiles.length===0)return {records:old,stale:true,reason:'No current source snapshot available; prior parsed records preserved.'};if(parsed.records.length===0&&old.length)return {records:old,stale:true,reason:'Current snapshot yielded zero parsed rows; prior records preserved pending parser/source review.'};return {records:parsed.records,stale:false,reason:null}}
const missing=preserveIfUnavailable(parse('POLICE_MISSING','person','/missing','MISSING'),'data/police-missing-latest.json');
const found=preserveIfUnavailable(parse('POLICE_FOUND','person','/found','LOCATED'),'data/police-found-latest.json');
const bodies=preserveIfUnavailable(parse('POLICE_DISASTER_BODIES','body','/dead-bodies','UNIDENTIFIED_BODY'),'data/police-bodies-latest.json');
const generated_at=new Date().toISOString();
for(const [file,x] of [['data/police-missing-latest.json',missing],['data/police-found-latest.json',found],['data/police-bodies-latest.json',bodies]])fs.writeFileSync(file,JSON.stringify({incident_id:INCIDENT,generated_at,stale:x.stale,stale_reason:x.reason,records:x.records},null,2)+'\n');
console.log(JSON.stringify({missing:missing.records.length,found:found.records.length,bodies:bodies.records.length,stale:{missing:missing.stale,found:found.stale,bodies:bodies.stale}},null,2));
